server:
  port: 8080

spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cards
    username: cards_user
    password: cards_pass
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
    contexts: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  security:
    card-encryption-key: ${CARD_ENCRYPTION_KEY:0123456789ABCDEF0123456789ABCDEF}
    card-hmac-key: ${CARD_HMAC_KEY:0123456789ABCDEF0123456789ABCDEF}
    jwt-access-secret: ${JWT_SECRET:0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF}
    jwt-access-ttl: 1h